config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to =>"homes#top"

  devise_for :users

   get "home/about"=>"homes#about"

  resources :books, only: [:index,:show,:edit,:create,:destroy,:update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index,:show,:edit,:update] do
   resource :relationships, only: [:create, :destroy]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
  end

 get "search" => "searches#search"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

  validates :comment,presence:true

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    comment = BookComment.new(book_comment_params)
    comment.user_id = current_user.id
    comment.book_id = @book.id
    comment.save
    @book_comment = BookComment.new
    
  end

  def destroy
    book_comment = BookComment.find(params[:id])
    book_comment.destroy
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new
    #redirect_to book_path(params[:book_id])

  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/views/book_comments/_book_comment.html.erb
<div>
  <% book.book_comments.each do |book_comment| %>
  <table class='table'>
    <tr>
      <td><%= image_tag book_comment.user.get_profile_image, size:"100x100" %></td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user == current_user %>
      <td><%= link_to 'Destroy', book_book_comment_path(book,book_comment) ,method: :DELETE, remote: true, class: "btn btn-sm btn-danger"%></td>
      <% end %>
    </tr>
  </table>
    <P><%= book_comment.user.name %></P>
  <% end %>
</div>
<div>
  <%= form_with(model: [book, book_comment], local: false) do |f| %>
    <div class="form-group">
      <%= f.text_area :comment, class: "form-control" %>
    </div>
    <%= f.submit "送信" %>
  <% end %>
</div>

app/views/book_comments/create.js.erb
$("#book_comment").html("<%= j(render "book_comments/book_comment", book: @book, book_comment: @book_comment) %>");

app/views/book_comments/destroy.js.erb
$("#book_comment").html("<%= j(render "book_comments/book_comment", book: @book, book_comment: @book_comment) %>");